class Autogenerated {
  bool? success;
  String? message;
  List<TownData>? data;
  String? erros;
  int? status;

  Autogenerated(
      {this.success, this.message, this.data, this.erros, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    if (json['data'] != null) {
      data = <TownData>[];
      json['data'].forEach((v) {
        data!.add(TownData.fromJson(v));
      });
    }
    erros = json['erros'];
    status = json['status'];
  }
}

class TownData {
  int? id;
  int? typeEventId;
  int? townId;
  Null createdAt;
  Null updatedAt;
  Town? town;

  TownData(
      {this.id,
      this.typeEventId,
      this.townId,
      this.createdAt,
      this.updatedAt,
      this.town});

  TownData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    typeEventId = json['type_event_id'];
    townId = json['town_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    town = json['town'] != null ? Town.fromJson(json['town']) : null;
  }
}

class Town {
  int? id;
  String? name;
  String? createdAt;
  String? updatedAt;

  Town({this.id, this.name, this.createdAt, this.updatedAt});

  Town.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }
}
